[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/hello/:name"
  to = "/.netlify/functions/hello-world/:name"
  status = 200

[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello-world"
  status = 200
